import {NextRequest,NextResponse} from "next/server";
import {docsSession} from "@/lib/auth";
import {audit,deleteDocumentRequirement,listDocumentRequirements,saveDocumentRequirement} from "@/lib/db";
import {apiError} from "@/lib/api-server";
import {cleanText} from "@/lib/security";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{if(!(await docsSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listDocumentRequirements(true));}catch(e){return apiError(e,'Belge gereksinimleri alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await docsSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const raw=await req.json();const name=cleanText(raw.name,160),program=cleanText(raw.program||'ALL',30);if(!name)return NextResponse.json({error:'Belge adı zorunlu'},{status:400});if(!/^[A-Z0-9-]+$/i.test(program))return NextResponse.json({error:'Program değeri geçersiz.'},{status:400});const b={id:Number(raw.id)||undefined,name,descr:cleanText(raw.descr,2000),program,required:raw.required!==false,active:raw.active!==false,sort_order:Math.max(0,Math.min(9999,Number(raw.sort_order)||0))};const r=await saveDocumentRequirement(b);await audit(s.email,b.id?'update':'create','document_requirement',String(r.id),{name:r.name,program:r.program});return NextResponse.json(r,{status:b.id?200:201});}catch(e){return apiError(e,'Belge gereksinimi kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await docsSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const id=Number((await req.json()).id);if(!Number.isFinite(id)||id<=0)return NextResponse.json({error:'Geçersiz kayıt.'},{status:400});await deleteDocumentRequirement(id);await audit(s.email,'delete','document_requirement',String(id));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Belge gereksinimi silinemedi.');}}
