-- RECF Türkiye — production schema
-- Supabase Dashboard → SQL Editor → Run

CREATE TABLE IF NOT EXISTS applications (
  id SERIAL PRIMARY KEY,
  num TEXT NOT NULL, team TEXT NOT NULL, org TEXT NOT NULL,
  city TEXT NOT NULL, type TEXT NOT NULL, program TEXT NOT NULL,
  mentor TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL,
  kit BOOLEAN NOT NULL DEFAULT FALSE,
  total INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'ÖDEME DOĞRULANDI',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  num TEXT NOT NULL UNIQUE, name TEXT NOT NULL, school TEXT NOT NULL,
  city TEXT NOT NULL, program TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS members (
  id SERIAL PRIMARY KEY,
  team_num TEXT NOT NULL, name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT '—', cat TEXT NOT NULL DEFAULT '—',
  consent TEXT NOT NULL DEFAULT '—', status TEXT NOT NULL DEFAULT 'DAVET GÖNDERİLDİ'
);

CREATE TABLE IF NOT EXISTS news (
  id SERIAL PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE, tag TEXT NOT NULL, title TEXT NOT NULL,
  excerpt TEXT NOT NULL, body TEXT NOT NULL DEFAULT '',
  published BOOLEAN NOT NULL DEFAULT FALSE,
  date TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams        ENABLE ROW LEVEL SECURITY;
ALTER TABLE members      ENABLE ROW LEVEL SECURITY;
ALTER TABLE news         ENABLE ROW LEVEL SECURITY;

-- This application accesses Postgres only from server-side routes using DATABASE_URL.
-- Do not expose DATABASE_URL to browser code or NEXT_PUBLIC_* variables.
