import {NextRequest,NextResponse} from "next/server";
import {contentSession} from "@/lib/auth";
import {audit,deleteEvent,getEvent,listEvents,slugify,upsertEvent} from "@/lib/db";
import {pathFromPublicUrl,PUBLIC_BUCKET,removeObject} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
import {cleanText,validHttpUrl} from "@/lib/security";
export const dynamic="force-dynamic";
async function cleanup(url?:string){const p=pathFromPublicUrl(url);if(p)await removeObject(PUBLIC_BUCKET,p).catch(()=>{});}
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await contentSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listEvents(all));}catch(e){return apiError(e,'Etkinlikler alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'CMS içerik düzenleme yetkisi gerekli.'},{status:401});const raw=await req.json();const title=cleanText(raw.title,180),code=cleanText(raw.code,30),city=cleanText(raw.city,80);const slug=slugify(cleanText(raw.slug||title,100));if(!slug||!title||!code||!city)return NextResponse.json({error:'Başlık, program ve şehir zorunlu'},{status:400});const cover=cleanText(raw.cover_url,1000);if(cover&&!validHttpUrl(cover))return NextResponse.json({error:'Kapak görseli URL’si geçersiz.'},{status:400});const b={...raw,slug,title,code,city,venue:cleanText(raw.venue,180),date_label:cleanText(raw.date_label,80),status:cleanText(raw.status||'KAYIT AÇIK',40),excerpt:cleanText(raw.excerpt,1000),body:cleanText(raw.body,100000),cover_url:cover,capacity:Math.max(1,Math.min(10000,Number(raw.capacity)||64)),published:!!raw.published,featured:!!raw.featured,registration_enabled:raw.registration_enabled!==false};const old:any=await getEvent(slug,true);const r=await upsertEvent(b);if(old?.cover_url&&old.cover_url!==r.cover_url)await cleanup(old.cover_url);await audit(s.email,'save','event',slug,{title});return NextResponse.json(r,{status:201});}catch(e){return apiError(e,'Etkinlik kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const slug=slugify(cleanText((await req.json()).slug,100));if(!slug)return NextResponse.json({error:'Geçersiz etkinlik.'},{status:400});const old:any=await getEvent(slug,true);await deleteEvent(slug);if(old?.cover_url)await cleanup(old.cover_url);await audit(s.email,'delete','event',slug);return NextResponse.json({ok:true});}catch(e){return apiError(e,'Etkinlik silinemedi.');}}
