"use client";
import { PUBLIC_CONTACT } from "@/lib/public-contact";
import ContactForm from "@/components/public/ContactForm";
import {Photo} from "@/components/Ui";
import {FigmaIcon,type FigmaIconName} from "@/components/FigmaIcon";

type Staff={id:number;name:string;public_title:string;public_bio:string;public_photo_url:string};
export default function AboutContent({settings,staff,about}:{settings:any;staff:Staff[];about:any}){
 const aboutBody=String(about?.body||"RECF Türkiye; robotik, drone ve STEM yarışma programlarının Türkiye’de sürdürülebilir, şeffaf ve öğrenci odaklı biçimde yürütülmesi için çalışan organizasyon yapısıdır. Türkiye operasyonları Intechne Teknoloji tarafından yürütülür.").split(/\n\n+/).filter(Boolean);
 const channels=[['DESTEK',settings.contact_info||PUBLIC_CONTACT.support,'Genel bilgi, teknik destek ve takım işlemleri'],['ETKİNLİK',settings.contact_team||PUBLIC_CONTACT.events,'Etkinlik, katılım ve kayıt işlemleri'],['TELEFON',settings.contact_phone||'—','Çalışma saatlerinde destek']];
 return <div className="safe-x mx-auto max-w-7xl lg:px-10"><section className="grid gap-6 lg:grid-cols-[1.45fr_1fr]"><div className="rounded-xl border-2 border-ink bg-white p-5 sm:p-7"><h2 className="font-display text-[19px] font-bold text-ink">BİZ KİMİZ?</h2>{aboutBody.map((p:string,i:number)=><p key={i} className="mt-3.5 whitespace-pre-line text-[15px] leading-[1.75] text-ink/65">{p}</p>)}</div><div className="grid gap-3">{([['saha','ETKİNLİK OPERASYONU','Saha, maç ve etkinlik süreçleri'],['mentor','EĞİTİM & MENTORLUK','Takım ve mentor gelişim süreçleri'],['ittifak','OKUL & PAYDAŞ İŞBİRLİĞİ','Kurum, okul ve partner programları'],['yayin','MEDYA & YAYIN','İçerik, yayın ve iletişim operasyonu']] as [FigmaIconName,string,string][]).map(r=><div key={r[1]} className="flex items-center gap-4 rounded-lg border border-ink/15 bg-white p-4"><FigmaIcon name={r[0]} className="h-7 w-7 shrink-0 text-ink"/><div><p className="font-display text-[13px] font-bold">{r[1]}</p><p className="text-xs text-ink/50">{r[2]}</p></div></div>)}</div></section>
 <section id="ekibimiz" className="scroll-mt-24 pt-16"><p className="font-display text-[12px] font-semibold tracking-[2px] text-cyan-deep">⬡ EKİBİMİZ</p><h2 className="mt-2 font-display text-[30px] font-bold text-ink">SAHANIN ARKASINDAKİ EKİP</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:gap-5">{staff.map(m=><article key={m.id} className="overflow-hidden rounded-xl border border-ink/15 bg-white">{m.public_photo_url?<img src={m.public_photo_url} alt={m.name} className="h-48 w-full object-cover"/>:<Photo label={m.name} tone="from-[#3d5778] to-ink" className="h-48 rounded-none"/>}<div className="p-4"><h3 className="font-display text-base font-bold">{m.name}</h3><p className="mt-1 font-display text-[11px] font-semibold tracking-wider text-cyan-deep">{m.public_title}</p>{m.public_bio&&<p className="mt-2 text-xs leading-relaxed text-ink/55">{m.public_bio}</p>}</div></article>)}{staff.length===0&&<div className="col-span-full rounded-xl border border-ink/15 bg-white p-7 text-ink/50">Ekibimizin tanıtımı yakında burada paylaşılacak.</div>}</div></section>
 <section id="iletisim" className="scroll-mt-24 pt-16"><h2 className="font-display text-[26px] font-bold text-ink">İLETİŞİM</h2><div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_1fr]"><div className="space-y-3">{channels.map(c=><div key={c[0]} className="flex flex-col items-start gap-2 rounded-lg border border-ink/15 bg-white p-4 sm:flex-row sm:items-center sm:gap-4"><span className="rounded bg-ink px-2.5 py-1.5 font-display text-[10px] font-bold tracking-wider text-cyan-brand">{c[0]}</span>{c[0]==='TELEFON'?<span className="w-full min-w-0 break-words font-semibold text-ink sm:w-auto sm:flex-1">{c[1]}</span>:<a href={`mailto:${c[1]}`} className="w-full min-w-0 break-words font-semibold text-ink underline decoration-ink/25 underline-offset-4 sm:w-auto sm:flex-1">{c[1]}</a>}<span className="w-full text-xs text-ink/45 sm:w-auto">{c[2]}</span></div>)}</div><ContactForm/></div></section></div>
}
