"use client";
import {useMemo,useState} from "react";
import {FigmaIcon,type FigmaIconName} from "@/components/FigmaIcon";
import {documentAvailability} from "@/lib/public-content";

type Doc={id:number;name:string;cat:string;size_label:string;url:string;file_path?:string;updated_label:string;downloads:number};
const officialManuals=[{name:"Engage · Tier Takeover",slug:"engage"},{name:"Achieve · Pinnacle",slug:"achieve"},{name:"Inspire · Pinnacle",slug:"inspire"},{name:"ADC · Fast Track",slug:"adc"},{name:"ADC Pro · Off Grid",slug:"pro"}];
const categoryMeta:Record<string,{icon:FigmaIconName;desc:string;hex:string}>={
  "Oyun Kılavuzları":{icon:"defter",desc:"Sezon oyun kuralları ve teknik kılavuzlar",hex:"#29B9E5"},
  "Formlar":{icon:"kayit",desc:"Takım, etkinlik ve izin formları",hex:"#8DC63F"},
  "Jüri Belgeleri":{icon:"rozet",desc:"Değerlendirme rubrikleri ve jüri kaynakları",hex:"#F2A900"},
  "Marka":{icon:"yildiz",desc:"Logo, marka ve iletişim kullanım dosyaları",hex:"#ED1C24"},
};
const fallback={icon:"defter" as FigmaIconName,desc:"Yayınlanmış kaynak ve dokümanlar",hex:"#29B9E5"};
export default function DocumentDirectory({initialItems}:{initialItems:Doc[]}){
  const [cat,setCat]=useState("TÜMÜ"),[q,setQ]=useState("");
  const cats=useMemo(()=>Array.from(new Set(initialItems.map(x=>x.cat).filter(Boolean))),[initialItems]);
  const shown=useMemo(()=>initialItems.filter(d=>(cat==="TÜMÜ"||d.cat===cat)&&(`${d.name} ${d.cat}`.toLowerCase().includes(q.toLowerCase()))),[initialItems,cat,q]);
  const activeMeta=cat==="TÜMÜ"?{icon:"defter" as FigmaIconName,desc:"Tüm yayınlanmış dokümanlar",hex:"#29B9E5"}:(categoryMeta[cat]||fallback);
  return <div className="safe-x mx-auto max-w-7xl lg:px-10">
    <section className="mb-8 rounded-xl border-2 border-ink bg-white p-5 sm:p-6" aria-labelledby="official-manuals-title"><h2 id="official-manuals-title" className="font-display text-xl font-bold">RESMÎ OYUN KILAVUZLARI</h2><p className="mt-2 text-sm leading-relaxed text-ink/60">İngilizce asıl kılavuzlar, güncel sürümler ve soru-cevaplar RECF’nin resmî oyun sitesinde yayımlanır. Türkçe dosyalar hazır olduğunda aşağıda ayrıca paylaşılır.</p><div className="mt-4 flex flex-wrap gap-2">{officialManuals.map(m=><a key={m.slug} href={`https://games.recf.org/${m.slug}`} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-md bg-ink px-4 py-2 text-xs font-bold text-white">{m.name} ↗</a>)}</div></section>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{["TÜMÜ",...cats].slice(0,4).map(c=>{const m=c==="TÜMÜ"?{icon:"defter" as FigmaIconName,desc:"Tüm yayınlanmış dosyalar",hex:"#29B9E5"}:(categoryMeta[c]||fallback);const count=c==="TÜMÜ"?initialItems.length:initialItems.filter(x=>x.cat===c).length;return <button key={c} onClick={()=>setCat(c)} className={`plate-hover min-w-0 rounded-xl border-2 border-ink bg-white p-5 text-left shadow-plateSm transition-all ${cat===c?"":"opacity-80 hover:opacity-100"}`} style={{["--tw-shadow-color" as string]:m.hex,outline:cat===c?`3px solid ${m.hex}`:"none",outlineOffset:2}} aria-pressed={cat===c}><FigmaIcon name={m.icon} className="h-8 w-8 text-ink"/><h2 className="mt-3 break-words font-display text-[15px] font-bold text-ink">{c}</h2><p className="mt-1.5 min-h-[38px] break-words text-[12.5px] leading-relaxed text-ink/55">{m.desc}</p><p className="mt-2.5 font-display text-[12px] font-semibold text-ink">{count} BELGE →</p></button>})}</div>
    {cats.length>3&&<div className="mt-4 flex flex-wrap gap-2">{cats.slice(3).map(c=><button key={c} onClick={()=>setCat(c)} className={`max-w-full break-words rounded-md border px-3.5 py-2 text-sm font-semibold ${cat===c?"border-ink bg-ink text-white":"border-ink/20 bg-white"}`}>{c}</button>)}</div>}
    <div className="mt-8 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-center gap-3"><FigmaIcon name={activeMeta.icon} className="h-6 w-6 shrink-0 text-ink"/><h2 className="break-words font-display text-[22px] font-bold text-ink">{cat==="TÜMÜ"?"TÜM DOKÜMANLAR":cat.toUpperCase()} 2026–27</h2></div><div className="relative w-full md:w-[320px]"><FigmaIcon name="rota" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink/35"/><input aria-label="Doküman ara" value={q} onChange={e=>setQ(e.target.value)} placeholder="Doküman ara…" className="w-full rounded-md border border-ink/20 bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:border-cyan-deep"/></div></div>
    <div className="mt-4 space-y-3.5">{shown.length===0?<p className="rounded-lg border border-ink/15 bg-white p-8 text-center text-ink/50">Yayınlanmış doküman bulunmuyor.</p>:shown.map(d=><div key={d.id} className="flex min-w-0 flex-wrap items-center gap-4 rounded-lg border-[1.5px] border-ink/20 bg-white px-4 py-4 sm:px-5"><span className="flex h-10 w-14 shrink-0 items-center justify-center rounded bg-cyan-brand/15 text-ink"><FigmaIcon name="defter" className="h-6 w-6"/></span><span className="min-w-0 flex-1"><span className="block break-words font-semibold text-ink">{d.name}</span><span className="block break-words text-[12.5px] text-ink/50">{d.cat}{d.updated_label?` · ${d.updated_label}`:""}</span></span>{d.size_label&&documentAvailability(d).available&&<span className="hidden shrink-0 rounded bg-paper px-2.5 py-1 font-display text-[11px] font-medium text-ink/60 sm:block">{d.size_label}</span>}{documentAvailability(d).available?<a href={`/api/documents/download?id=${d.id}`} target="_blank" rel="noreferrer" className="flex min-h-11 w-full items-center justify-center rounded-md bg-ink px-4 py-2.5 font-display text-[12px] font-bold text-white transition-colors hover:bg-cyan-deep sm:w-auto">İNDİR / AÇ</a>:<span className="flex min-h-11 w-full items-center justify-center rounded-md bg-paper px-4 py-2.5 text-xs font-semibold text-ink/60 sm:w-auto">{documentAvailability(d).message}</span>}</div>)}</div>
    <p className="mt-6 text-[13px] text-ink/45">Kılavuzların İngilizce asılları RECF resmi kaynaklarında yayınlanır; Türkçe çeviriler RECF Türkiye tarafından sağlanır. Çeviri yayımlanmamışsa dosya bağlantısı gösterilmez. Sürüm farkında İngilizce asıl geçerlidir.</p>
  </div>;
}
