import {NextRequest,NextResponse} from "next/server";
import {adminSession,cmsSession} from "@/lib/auth";
import {audit,deleteTeam,getTeam,listTeamDocs,listTeams,updateTeam} from "@/lib/db";
import {pathFromPublicUrl,PRIVATE_BUCKET,PUBLIC_BUCKET,removeObject} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await cmsSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listTeams(all));}catch(e){return apiError(e,'Takımlar alınamadı.');}}
export async function PUT(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:'Bu işlem için admin yetkisi gerekli.'},{status:401});const b=await req.json();const num=String(b.num||'').trim().toUpperCase();if(!/^[A-Z0-9-]{2,10}$/.test(num)||!b.name||!b.school||!b.city||!b.program)return NextResponse.json({error:'Takım no ve zorunlu alanlar eksik/geçersiz'},{status:400});const old:any=await getTeam(num);const r=await updateTeam(num,{...b,num});if(old?.logo_url&&old.logo_url!==r?.logo_url){const p=pathFromPublicUrl(old.logo_url);if(p)await removeObject(PUBLIC_BUCKET,p).catch(()=>{});}await audit(s.email,old?'update':'create','team',num,{name:b.name});return NextResponse.json(r);}catch(e){return apiError(e,'Takım kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:'Bu işlem için admin yetkisi gerekli.'},{status:401});const {num}=await req.json();const team:any=await getTeam(String(num));if(!team)return NextResponse.json({error:'Takım yok'},{status:404});const docs:any[]=await listTeamDocs(String(num));for(const d of docs)if(d.file_path)await removeObject(PRIVATE_BUCKET,d.file_path).catch(()=>{});const logo=pathFromPublicUrl(team.logo_url);if(logo)await removeObject(PUBLIC_BUCKET,logo).catch(()=>{});await deleteTeam(String(num));await audit(s.email,'delete','team',String(num));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Takım silinemedi.');}}
