import {NextRequest,NextResponse} from "next/server";
import {adminSession,approvalsSession} from "@/lib/auth";
import {audit,deleteTeam,getTeam,listTeamDocs,listTeams,updateTeam} from "@/lib/db";
import {pathFromPublicUrl,PRIVATE_BUCKET,PUBLIC_BUCKET,removeObject,safeStoragePath} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
import {cleanText,validEmail,validHttpUrl} from "@/lib/security";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await approvalsSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listTeams(all));}catch(e){return apiError(e,'Takımlar alınamadı.');}}
export async function PUT(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:'Bu işlem için admin yetkisi gerekli.'},{status:403});const b=await req.json();const num=cleanText(b.num,10).toUpperCase();const name=cleanText(b.name,120),school=cleanText(b.school,160),city=cleanText(b.city,80),district=cleanText(b.district,80),program=cleanText(b.program,20);if(!/^[A-Z0-9-]{2,10}$/.test(num)||!name||!school||!city||!['engage','achieve','inspire','adc','adc-pro'].includes(program))return NextResponse.json({error:'Takım no ve zorunlu alanlar eksik/geçersiz'},{status:400});const mentorEmail=cleanText(b.mentor_email,254).toLowerCase();if(mentorEmail&&!validEmail(mentorEmail))return NextResponse.json({error:'Mentor e-posta adresi geçersiz.'},{status:400});const logo=cleanText(b.logo_url,1000);if(logo&&!validHttpUrl(logo))return NextResponse.json({error:'Logo URL geçersiz.'},{status:400});const old:any=await getTeam(num);const r=await updateTeam(num,{...b,num,name,school,city,district,program,mentor_name:cleanText(b.mentor_name,120),mentor_email:mentorEmail,phone:cleanText(b.phone,40),slogan:cleanText(b.slogan,300),logo_url:logo});if(old?.logo_url&&old.logo_url!==r?.logo_url){const p=pathFromPublicUrl(old.logo_url);if(p&&safeStoragePath(p,'media'))await removeObject(PUBLIC_BUCKET,p).catch(()=>{});}await audit(s.email,old?'update':'create','team',num,{name});return NextResponse.json(r);}catch(e){return apiError(e,'Takım kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:'Bu işlem için admin yetkisi gerekli.'},{status:403});const {num}=await req.json();const teamNum=cleanText(num,20);const team:any=await getTeam(teamNum);if(!team)return NextResponse.json({error:'Takım yok'},{status:404});const docs:any[]=await listTeamDocs(teamNum);for(const d of docs)if(d.file_path&&safeStoragePath(String(d.file_path),`teams/${teamNum}/documents`))await removeObject(PRIVATE_BUCKET,d.file_path).catch(()=>{});const logo=pathFromPublicUrl(team.logo_url);if(logo)await removeObject(PUBLIC_BUCKET,logo).catch(()=>{});await deleteTeam(teamNum);await audit(s.email,'delete','team',teamNum);return NextResponse.json({ok:true});}catch(e){return apiError(e,'Takım silinemedi.');}}
