import {NextRequest,NextResponse} from "next/server";
import {cmsSession,docsSession,portalSession} from "@/lib/auth";
import {createTeamDoc,deleteTeamDoc,getTeamDoc,listTeamDocs,updateTeamDoc} from "@/lib/db";
import {createPrivateDownload,PRIVATE_BUCKET,removeObject} from "@/lib/storage";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){const download=Number(req.nextUrl.searchParams.get('download'));const cms=await cmsSession(req);const portal=await portalSession(req);let teamNum=req.nextUrl.searchParams.get('teamNum')||portal?.teamNum||'';if(!cms&&!portal)return NextResponse.json({error:'Yetkisiz'},{status:401});if(portal&&teamNum!==portal.teamNum)teamNum=portal.teamNum||'';const docs=await listTeamDocs(cms&&req.nextUrl.searchParams.get('all')==='1'?undefined:teamNum);if(download){const d=docs.find((x:any)=>Number(x.id)===download);if(!d?.file_path)return NextResponse.json({error:'Dosya yok'},{status:404});return NextResponse.json({url:await createPrivateDownload(d.file_path)});}return NextResponse.json(docs);}
export async function POST(req:NextRequest){const s=await portalSession(req);if(!s?.teamNum)return NextResponse.json({error:'Yetkisiz'},{status:401});const b=await req.json();if(!b.file_path)return NextResponse.json({error:'Yüklenen dosya bilgisi zorunlu'},{status:400});if(b.id){const old:any=await getTeamDoc(Number(b.id),s.teamNum);if(!old)return NextResponse.json({error:'Belge bulunamadı'},{status:404});const r=await updateTeamDoc(Number(b.id),s.teamNum,{file_path:b.file_path,mime_type:b.mime_type??'',status:'İNCELEMEDE',review_note:'',date_label:new Date().toLocaleDateString('tr-TR')});if(old.file_path&&old.file_path!==b.file_path)await removeObject(PRIVATE_BUCKET,old.file_path).catch(()=>{});return NextResponse.json(r,{status:201});}if(!String(b.name||'').trim())return NextResponse.json({error:'Belge adı zorunlu'},{status:400});return NextResponse.json(await createTeamDoc(s.teamNum,{name:String(b.name).trim(),descr:String(b.descr||''),required:false,file_path:b.file_path,mime_type:b.mime_type??'',status:'İNCELEMEDE',date_label:new Date().toLocaleDateString('tr-TR')}),{status:201});}
export async function PATCH(req:NextRequest){const s=await docsSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const b=await req.json();if(!b.team_num)return NextResponse.json({error:'Takım gerekli'},{status:400});return NextResponse.json(await updateTeamDoc(Number(b.id),String(b.team_num),{status:b.status,review_note:b.review_note??'',date_label:new Date().toLocaleDateString('tr-TR')}));}
export async function DELETE(req:NextRequest){const portal=await portalSession(req);const cms=await docsSession(req);if(!portal&&!cms)return NextResponse.json({error:'Yetkisiz'},{status:401});const b=await req.json();const teamNum=portal?.teamNum||String(b.team_num||'');if(!teamNum)return NextResponse.json({error:'Takım yok'},{status:400});const old:any=await getTeamDoc(Number(b.id),teamNum);if(!old)return NextResponse.json({error:'Belge yok'},{status:404});if(portal&&old.requirement_id)return NextResponse.json({error:'Zorunlu belge satırı silinemez; yeni dosya yükleyebilirsiniz.'},{status:400});const removed=await deleteTeamDoc(Number(b.id),teamNum);if(removed?.file_path)await removeObject(PRIVATE_BUCKET,removed.file_path).catch(()=>{});return NextResponse.json({ok:true});}
