import { NextRequest, NextResponse } from "next/server";
import { portalSession } from "@/lib/auth";
import { audit, getTeam, listPayments, listTeamDocs, updateTeam } from "@/lib/db";
import { pathFromPublicUrl, safeStoragePath } from "@/lib/storage";
import { cleanText, validEmail } from "@/lib/security";
import { apiError } from "@/lib/api-server";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const s=await portalSession(req);if(!s?.teamNum)return NextResponse.json({error:"Yetkisiz"},{status:401});const team=await getTeam(s.teamNum);if(!team)return NextResponse.json({error:"Takım bulunamadı"},{status:404});return NextResponse.json({num:s.teamNum,profile:team,docs:await listTeamDocs(s.teamNum),payments:await listPayments(s.teamNum)});}catch(e){return apiError(e,'Takım bilgileri alınamadı.');}}
export async function PUT(req:NextRequest){try{const s=await portalSession(req);if(!s?.teamNum)return NextResponse.json({error:"Yetkisiz"},{status:401});const current=await getTeam(s.teamNum);if(!current)return NextResponse.json({error:"Takım yok"},{status:404});const b=await req.json();const email=cleanText(b.mentor_email??current.mentor_email,254).toLowerCase();if(email&&!validEmail(email))return NextResponse.json({error:'Mentor e-posta adresi geçersiz.'},{status:400});let logo=cleanText(b.logo_url??current.logo_url,1000);if(logo!==current.logo_url){const p=pathFromPublicUrl(logo);if(!p||!safeStoragePath(p,`teams/${s.teamNum}/logo`))return NextResponse.json({error:'Takım logosu yalnızca kendi takım Storage alanınızdan seçilebilir.'},{status:400});}const allowed={...current,name:cleanText(b.name??current.name,120),school:cleanText(b.school??current.school,160),city:cleanText(b.city??current.city,80),district:cleanText(b.district??current.district,80),program:current.program,status:current.status,visible:current.visible,mentor_name:cleanText(b.mentor_name??current.mentor_name,120),mentor_email:email,phone:cleanText(b.phone??current.phone,40),slogan:cleanText(b.slogan??current.slogan,300),logo_url:logo};const r=await updateTeam(s.teamNum,allowed);await audit(s.email,'portal_update','team',s.teamNum,{name:r?.name});return NextResponse.json(r);}catch(e){return apiError(e,'Takım profili güncellenemedi.');}}
