"use client";
import {useEffect,useState} from "react";
import {PageHead,Photo} from "@/components/Ui";

type Staff={id:number;name:string;public_title:string;public_bio:string;public_photo_url:string};
export default function HakkimizdaPage(){
 const [settings,setSettings]=useState<any>({}),[staff,setStaff]=useState<Staff[]>([]),[about,setAbout]=useState<any>(null),[form,setForm]=useState({name:'',email:'',phone:'',subject:'Genel',message:''}),[msg,setMsg]=useState('');
 useEffect(()=>{Promise.all([fetch('/api/settings').then(r=>r.json()),fetch('/api/staff').then(r=>r.ok?r.json():[]),fetch('/api/pages/hakkimizda').then(r=>r.ok?r.json():null)]).then(([s,st,p])=>{setSettings(s);setStaff(st);setAbout(p)}).catch(()=>{})},[]);
 async function send(e:React.FormEvent){e.preventDefault();setMsg('Gönderiliyor…');const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)return setMsg('⚠ '+(j.error||'Mesaj gönderilemedi.'));setMsg('✓ Mesajınız alındı.');setForm({name:'',email:'',phone:'',subject:'Genel',message:''})}
 const aboutBody=String(about?.body||"RECF Türkiye; robotik, drone ve STEM yarışma programlarının Türkiye’de sürdürülebilir, şeffaf ve öğrenci odaklı biçimde yürütülmesi için çalışan organizasyon yapısıdır. Türkiye operasyonları Intechne Teknoloji tarafından yürütülür.").split(/\n\n+/).filter(Boolean);
 const channels=[['GENEL',settings.contact_info||'info@recfturkiye.org','Genel bilgi ve kurumsal iletişim'],['TAKIM DESTEĞİ',settings.contact_team||'takim@recfturkiye.org','Kayıt, portal ve takım işlemleri'],['TELEFON',settings.contact_phone||'—','Çalışma saatlerinde destek']];
 return <div className="pb-20"><PageHead kicker="KURUMSAL" title={about?.title?.toUpperCase()||"RECF TÜRKİYE HAKKINDA"}/><div className="mx-auto max-w-7xl px-5 lg:px-10"><section className="grid gap-6 lg:grid-cols-[1.45fr_1fr]"><div className="rounded-xl border-2 border-ink bg-white p-7"><h2 className="font-display text-[19px] font-bold text-ink">BİZ KİMİZ?</h2>{aboutBody.map((p:string,i:number)=><p key={i} className="mt-3.5 whitespace-pre-line text-[15px] leading-[1.75] text-ink/65">{p}</p>)}</div><div className="grid gap-3">{[['🏟','ETKİNLİK OPERASYONU','Saha, maç ve etkinlik süreçleri'],['🎓','EĞİTİM & MENTORLUK','Takım ve mentor gelişim süreçleri'],['🤝','OKUL & PAYDAŞ İŞBİRLİĞİ','Kurum, okul ve partner programları'],['📡','MEDYA & YAYIN','İçerik, yayın ve iletişim operasyonu']].map(r=><div key={r[1]} className="flex items-center gap-4 rounded-lg border border-ink/15 bg-white p-4"><span className="text-2xl">{r[0]}</span><div><p className="font-display text-[13px] font-bold">{r[1]}</p><p className="text-xs text-ink/50">{r[2]}</p></div></div>)}</div></section>
 <section id="ekibimiz" className="scroll-mt-24 pt-16"><p className="font-display text-[12px] font-semibold tracking-[2px] text-cyan-deep">⬡ EKİBİMİZ</p><h2 className="mt-2 font-display text-[30px] font-bold text-ink">SAHANIN ARKASINDAKİ EKİP</h2><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{staff.map(m=><article key={m.id} className="overflow-hidden rounded-xl border border-ink/15 bg-white">{m.public_photo_url?<img src={m.public_photo_url} alt={m.name} className="h-48 w-full object-cover"/>:<Photo label={m.name} tone="from-[#3d5778] to-ink" className="h-48 rounded-none"/>}<div className="p-4"><h3 className="font-display text-base font-bold">{m.name}</h3><p className="mt-1 font-display text-[11px] font-semibold tracking-wider text-cyan-deep">{m.public_title}</p>{m.public_bio&&<p className="mt-2 text-xs leading-relaxed text-ink/55">{m.public_bio}</p>}</div></article>)}{staff.length===0&&<div className="col-span-full rounded-xl border border-ink/15 bg-white p-7 text-ink/50">Public ekip profilleri CMS → Ekip & Yetkiler bölümünden yayınlanabilir.</div>}</div></section>
 <section id="iletisim" className="scroll-mt-24 pt-16"><h2 className="font-display text-[26px] font-bold text-ink">İLETİŞİM</h2><div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_1fr]"><div className="space-y-3">{channels.map(c=><div key={c[0]} className="flex flex-wrap items-center gap-4 rounded-lg border border-ink/15 bg-white p-4"><span className="rounded bg-ink px-2.5 py-1.5 font-display text-[10px] font-bold tracking-wider text-cyan-brand">{c[0]}</span><span className="min-w-0 flex-1 font-semibold text-ink">{c[1]}</span><span className="text-xs text-ink/45">{c[2]}</span></div>)}</div><form onSubmit={send} className="rounded-xl bg-ink p-6"><h3 className="font-display text-[17px] font-bold text-cyan-brand">HIZLI MESAJ</h3><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Adınız Soyadınız" className="mt-3 w-full rounded-md border border-white/25 bg-white/[.08] px-3.5 py-3 text-sm text-white placeholder:text-white/45 outline-none focus:border-cyan-brand"/><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="E-posta" className="mt-3 w-full rounded-md border border-white/25 bg-white/[.08] px-3.5 py-3 text-sm text-white placeholder:text-white/45 outline-none focus:border-cyan-brand"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Telefon (opsiyonel)" className="mt-3 w-full rounded-md border border-white/25 bg-white/[.08] px-3.5 py-3 text-sm text-white placeholder:text-white/45 outline-none focus:border-cyan-brand"/><select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} className="mt-3 w-full rounded-md border border-white/25 bg-[#1d2638] px-3.5 py-3 text-sm text-white outline-none focus:border-cyan-brand"><option>Genel</option><option>Takım Desteği</option><option>Kurumsal</option><option>Basın</option><option>Gönüllülük</option></select><textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Mesajınız…" rows={5} className="mt-3 w-full rounded-md border border-white/25 bg-white/[.08] px-3.5 py-3 text-sm text-white placeholder:text-white/45 outline-none focus:border-cyan-brand"/>{msg&&<p className="mt-3 text-sm text-cyan-brand">{msg}</p>}<button type="submit" className="mt-4 w-full rounded-md bg-cyan-brand py-3.5 font-display text-sm font-bold text-ink hover:bg-white">GÖNDER</button></form></div></section></div></div>
}
