// Yerel geliştirme / boş veritabanı için gömülü program içerikleri.
// Canlıda program_content tablosu doluysa DB her zaman önceliklidir (CMS'ten yönetilir).
export const FALLBACK_PROGRAMS = [
  {
    slug: "engage", code: "ENG", name: "RECF Engage", game: "Tier Takeover",
    age: "U12 · U15", age_detail: "İlkokul ve ortaokul takımları",
    color_hex: "#29B9E5",
    short: "Rekabetçi robotiğe ilk adım — solo sürüş, solo kodlama ve ittifak maçlarıyla.",
    long: "RECF Engage, ilkokul ve ortaokul öğrencilerini Tier Takeover oyunuyla rekabetçi robotikle tanıştırır. Takımlar aynı sahada hem sürüş hem kodlama becerilerini geliştirir; ittifak maçlarında iki takım ortak skor için birlikte oynar.",
    chips: ["Solo Sürüş", "Solo Kodlama", "İttifak Maçı", "Mühendislik Defteri"],
    match_types: [
      { title: "SOLO SÜRÜŞ", desc: "2-3 üye sahada robotu sürerek 60 saniyede puan toplar." },
      { title: "SOLO KODLAMA", desc: "Robot, öğrencilerin yazdığı kodla tamamen otonom skorlar." },
      { title: "İTTİFAK MAÇI", desc: "İki takım tek ortak skor için aynı sahada birlikte oynar." },
      { title: "DEFTER & MÜLAKAT", desc: "Mühendislik defteri ve jüri görüşmesi sezon puanına işler." },
    ],
    facts: [
      { label: "Yaş Grubu", value: "U12 · U15" },
      { label: "Sezon Oyunu", value: "Tier Takeover" },
      { label: "Takım Boyu", value: "2–10 öğrenci" },
      { label: "Maç Süresi", value: "60 sn" },
      { label: "Resmî Kaynak", value: "games.recf.org/engage" },
    ],
    source: "https://games.recf.org/engage/2.0", cover_url: "", active: true, sort_order: 1,
  },
  {
    slug: "achieve", code: "ACH", name: "RECF Achieve", game: "Pinnacle",
    age: "U15 · U19", age_detail: "Ortaokul ve lise takımları",
    color_hex: "#1E8CD9",
    short: "Lise seviyesinde tam rekabet — Pinnacle sahasında sürüş, kod ve ittifak stratejisi.",
    long: "RECF Achieve, ortaokul ve lise öğrencilerini Pinnacle oyunuyla zorlar. Solo sürüş ve solo kodlama maçlarının yanında ittifak formatı, strateji ve iletişimi sezonun merkezine koyar. Türkiye Şampiyonası kotaları bu programdan dağıtılır.",
    chips: ["Solo Sürüş", "Solo Kodlama", "İttifak Maçı", "Türkiye Şampiyonası Kotası"],
    match_types: [
      { title: "SOLO SÜRÜŞ", desc: "3 üyeye kadar saha ekibi; sürücü değişimli 60 saniye." },
      { title: "SOLO KODLAMA", desc: "Tam otonom skor — sensör ve rota optimizasyonu belirleyici." },
      { title: "İTTİFAK MAÇI", desc: "Kırmızı/mavi ittifak çiftleri ortak skor için yarışır." },
      { title: "ELEME TURLARI", desc: "Kalifikasyon sıralaması ittifak seçimini, seçim finali belirler." },
    ],
    facts: [
      { label: "Yaş Grubu", value: "U15 · U19" },
      { label: "Sezon Oyunu", value: "Pinnacle" },
      { label: "Takım Boyu", value: "2–10 öğrenci" },
      { label: "Maç Süresi", value: "60 sn" },
      { label: "Resmî Kaynak", value: "games.recf.org/achieve" },
    ],
    source: "https://games.recf.org/achieve/2.0", cover_url: "", active: true, sort_order: 2,
  },
  {
    slug: "inspire", code: "INS", name: "RECF Inspire", game: "Pinnacle",
    age: "Üniversite", age_detail: "Ön lisans, lisans ve lisansüstü takımları",
    color_hex: "#10192F",
    short: "Üniversite ligi — aynı Pinnacle sahası, daha yüksek mühendislik çıtası.",
    long: "RECF Inspire, üniversite öğrencilerini Pinnacle oyununda buluşturur. Altı kişiye kadar saha ekibiyle oynanan format; ileri mekanizma tasarımı, otonomi ve takım yönetimini öne çıkarır. Kariyer köprüsü TechApp profillerine doğrudan işler.",
    chips: ["Üniversite Ligi", "İleri Otonomi", "6 Kişilik Saha Ekibi", "Kariyer Köprüsü"],
    match_types: [
      { title: "SOLO SÜRÜŞ", desc: "6 üyeye kadar saha ekibi aynı maçta görev paylaşır." },
      { title: "SOLO KODLAMA", desc: "Çok robotlu otonom koordinasyon en yüksek tavanı sunar." },
      { title: "İTTİFAK MAÇI", desc: "Üniversiteler arası ittifaklar ortak skor için eşleşir." },
      { title: "TEKNİK SUNUM", desc: "Tasarım kararları jüri önünde mühendislik diliyle savunulur." },
    ],
    facts: [
      { label: "Yaş Grubu", value: "Üniversite" },
      { label: "Sezon Oyunu", value: "Pinnacle" },
      { label: "Saha Ekibi", value: "6 üyeye kadar" },
      { label: "Maç Süresi", value: "60 sn" },
      { label: "Resmî Kaynak", value: "games.recf.org/inspire" },
    ],
    source: "https://games.recf.org/inspire/2.0", cover_url: "", active: true, sort_order: 3,
  },
  {
    slug: "adc", code: "ADC", name: "Aerial Drone Competition", game: "Mission 2027: Fast Track",
    age: "U15 · U19", age_detail: "Ortaokul ve lise drone takımları",
    color_hex: "#8DC63F",
    short: "Drone sahasında dört görev: pilotaj, otonom uçuş, teamwork ve iletişim.",
    long: "Aerial Drone Competition, öğrencileri Mission 2027: Fast Track görevlerinde hem pilot hem programcı olarak zorlar. Solo pilotaj ve solo otonom uçuşun yanında 90 saniyelik teamwork maçı ve iletişim görevi sezon skorunu oluşturur.",
    chips: ["Solo Pilotaj", "Solo Otonom Uçuş", "Teamwork Maçı", "İletişim Görevi"],
    match_types: [
      { title: "SOLO PİLOTAJ", desc: "60 saniyelik parkur uçuşu — keyhole ve iniş puanları." },
      { title: "SOLO OTONOM", desc: "Tam kodlu uçuş; spiral bonus ve tunnel geçişleri." },
      { title: "TEAMWORK", desc: "İki takım 90 saniyede ortak skor için birlikte uçar." },
      { title: "İLETİŞİM", desc: "Takım süreçlerini anlatan sunum görevi puana işler." },
    ],
    facts: [
      { label: "Yaş Grubu", value: "U15 · U19" },
      { label: "Sezon Görevi", value: "Mission 2027: Fast Track" },
      { label: "Maç Süresi", value: "60 / 90 sn" },
      { label: "Saha", value: "Kapalı alan drone sahası" },
      { label: "Resmî Kaynak", value: "games.recf.org (ADC)" },
    ],
    source: "https://games.recf.org/", cover_url: "", active: true, sort_order: 4,
  },
  {
    slug: "adc-pro", code: "PRO", name: "ADC Pro", game: "Off Grid",
    age: "U19 · Üniversite", age_detail: "Lise ve üniversite kategorileri; yaş ve uygunluk koşulları resmî kılavuzda açıklanır.",
    color_hex: "#93268F",
    short: "Drone ve kara robotuyla pilotaj, otonom, ittifak ve iletişim görevleri.",
    long: "Off Grid, drone ve kara robotunun birlikte görev yaptığı bir yarışmadır. Solo pilotaj ve solo otonom maçları 60 saniye, ikişer takımlı ittifak maçları 120 saniyedir. Takımlar ayrıca yarışma defteri ve jüri görüşmesiyle iletişim görevine katılır.",
    chips: ["Solo Pilotaj", "Solo Otonom", "2v2 İttifak", "İletişim"],
    match_types: [
      { title: "SOLO PİLOTAJ", desc: "60 saniye; drone ve robot uzaktan kontrol edilir." },
      { title: "SOLO OTONOM", desc: "60 saniye; drone ve robot önceden yazılmış kodla çalışır." },
      { title: "İTTİFAK / TEAMWORK", desc: "120 saniye; iki takımlı kırmızı ve mavi ittifaklar yarışır." },
      { title: "İLETİŞİM", desc: "Yarışma defteri ve jüri görüşmesi." },
    ],
    facts: [
      { label: "Kategori", value: "U19 · Üniversite" },
      { label: "Sezon Görevi", value: "Off Grid" },
      { label: "Solo Maç", value: "60 saniye" },
      { label: "İttifak Maçı", value: "120 saniye" },
      { label: "Kılavuz", value: "v2.0" },
    ],
    source: "https://games.recf.org/pro/2.0", cover_url: "", active: true, sort_order: 5,
  },
];
export const fallbackProgram = (slug: string) => FALLBACK_PROGRAMS.find(p => p.slug === slug) ?? null;
