import { NextRequest, NextResponse } from "next/server";
import { approvalsSession, portalSession } from "@/lib/auth";
import { audit, deletePayment, listPayments, savePayment } from "@/lib/db";
import {apiError} from "@/lib/api-server";
import {cleanText} from "@/lib/security";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const p=await portalSession(req);if(p?.teamNum)return NextResponse.json(await listPayments(p.teamNum));if(!(await approvalsSession(req)))return NextResponse.json({error:"Yetkisiz"},{status:403});return NextResponse.json(await listPayments(cleanText(req.nextUrl.searchParams.get("teamNum"),20)||undefined));}catch(e){return apiError(e,'Ödemeler alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await approvalsSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await req.json();const team_num=cleanText(b.team_num,20),ref=cleanText(b.ref,120),item=cleanText(b.item,160),date_label=cleanText(b.date_label,40),amount_label=cleanText(b.amount_label,80),status=cleanText(b.status,30);if(!team_num||!item||!amount_label||!['BEKLİYOR','ÖDENDİ','İPTAL','MUAF'].includes(status))return NextResponse.json({error:'Ödeme bilgileri eksik/geçersiz.'},{status:400});const r=await savePayment({...b,team_num,ref,item,date_label,amount_label,status});await audit(s.email,b.id?'update':'create','payment',String(r?.id||b.id),{team_num,status});return NextResponse.json(r,{status:b.id?200:201});}catch(e){return apiError(e,'Ödeme kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await approvalsSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const {id}=await req.json();await deletePayment(Number(id));await audit(s.email,'delete','payment',String(id));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Ödeme silinemedi.');}}
