import { NextRequest, NextResponse } from "next/server";
import { adminSession } from "@/lib/auth";
import {audit,deleteUser,listUsers,saveUser,tempPassword} from "@/lib/db";
import {apiError} from "@/lib/api-server";
import {cleanText,validEmail} from "@/lib/security";
import {generateTotpSecret,totpUri} from "@/lib/totp";
export const dynamic="force-dynamic";
const ROLES=['admin','editor','approvals','technical','mentor'];
export async function GET(req:NextRequest){try{if(!(await adminSession(req)))return NextResponse.json({error:"Yetkisiz"},{status:403});return NextResponse.json(await listUsers());}catch(e){return apiError(e,'Kullanıcılar alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await req.json();const email=cleanText(b.email,254).toLowerCase(),name=cleanText(b.name,120),role=cleanText(b.role,20);if(!validEmail(email)||!name||!ROLES.includes(role))return NextResponse.json({error:"Geçerli e-posta, ad ve rol zorunlu"},{status:400});if(role==='mentor'&&!cleanText(b.team_num,20))return NextResponse.json({error:'Mentor hesabı için takım numarası zorunlu.'},{status:400});let generated="";if(!b.password){generated=tempPassword();b.password=generated;}else if(String(b.password).length<12)return NextResponse.json({error:'Şifre en az 12 karakter olmalı.'},{status:400});let mfaSecret="";if(b.enable_mfa===true&&role!=='mentor'){mfaSecret=generateTotpSecret();b._mfaSecret=mfaSecret;}const r=await saveUser({...b,email,name,role,team_num:cleanText(b.team_num,20)});await audit(s.email,"create","user",String(r.id),{email,role,mfa:!!mfaSecret});return NextResponse.json({...r,temporaryPassword:generated||undefined,mfaSetupKey:mfaSecret||undefined,mfaUri:mfaSecret?totpUri(mfaSecret,email):undefined},{status:201});}catch(e){return apiError(e,'Kullanıcı oluşturulamadı.');}}
export async function PUT(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await req.json();const email=cleanText(b.email,254).toLowerCase(),name=cleanText(b.name,120),role=cleanText(b.role,20);if(!Number.isFinite(Number(b.id))||!validEmail(email)||!name||!ROLES.includes(role))return NextResponse.json({error:'Kullanıcı bilgileri geçersiz.'},{status:400});if(b.password&&String(b.password).length<12)return NextResponse.json({error:'Yeni şifre en az 12 karakter olmalı.'},{status:400});let mfaSecret="";if(b.reset_mfa===true&&role!=='mentor'){mfaSecret=generateTotpSecret();b._mfaSecret=mfaSecret;}const r=await saveUser({...b,email,name,role,team_num:cleanText(b.team_num,20)});await audit(s.email,"update","user",String(b.id),{email,role,mfa_reset:!!mfaSecret,mfa_cleared:b.clear_mfa===true});return NextResponse.json({...r,mfaSetupKey:mfaSecret||undefined,mfaUri:mfaSecret?totpUri(mfaSecret,email):undefined});}catch(e){return apiError(e,'Kullanıcı güncellenemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await adminSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const {id}=await req.json();await deleteUser(Number(id));await audit(s.email,"delete","user",String(id));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Kullanıcı silinemedi.');}}
