import {NextRequest,NextResponse} from "next/server";
import {contentSession} from "@/lib/auth";
import {addDocument,audit,deleteDocument,getDocument,listDocuments,updateDocument} from "@/lib/db";
import {PUBLIC_BUCKET,removeObject} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await contentSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listDocuments(all));}catch(e){return apiError(e,'Dokümanlar alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'CMS içerik düzenleme yetkisi gerekli.'},{status:401});const b=await req.json();if(!b.name||!b.cat||!b.url)return NextResponse.json({error:'Ad, kategori ve dosya/URL zorunlu'},{status:400});const r=await addDocument(b);await audit(s.email,'create','document',String(r.id),{name:b.name});return NextResponse.json(r,{status:201});}catch(e){return apiError(e,'Doküman kaydedilemedi.');}}
export async function PUT(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const b=await req.json();if(!b.name||!b.cat||!b.url)return NextResponse.json({error:'Ad, kategori ve dosya/URL zorunlu'},{status:400});const old:any=await getDocument(Number(b.id));const r=await updateDocument(Number(b.id),b);if(old?.file_path&&old.file_path!==r?.file_path)await removeObject(PUBLIC_BUCKET,old.file_path).catch(()=>{});await audit(s.email,'update','document',String(b.id),{name:b.name});return NextResponse.json(r);}catch(e){return apiError(e,'Doküman güncellenemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const {id}=await req.json();const old=await deleteDocument(Number(id));if(old?.file_path)await removeObject(PUBLIC_BUCKET,old.file_path).catch(()=>{});await audit(s.email,'delete','document',String(id));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Doküman silinemedi.');}}
