import { NextRequest, NextResponse } from "next/server";
import { approvalsSession, portalSession } from "@/lib/auth";
import { audit, cancelEventRegistration, listEventRegistrations, registerEvent, updateEventRegistration } from "@/lib/db";
import {apiError} from "@/lib/api-server";
export const dynamic="force-dynamic";
const SAFE_ERRORS=['Etkinlik bulunamadı.','Etkinlik kaydı kapalı.','Takım aktif değil.','Bu etkinlik takım programınız için değil.','Etkinlik kontenjanı dolu.'];
export async function GET(req:NextRequest){try{const p=await portalSession(req);if(p?.teamNum)return NextResponse.json(await listEventRegistrations(undefined,p.teamNum));if(!(await approvalsSession(req)))return NextResponse.json({error:"Yetkisiz"},{status:403});const eventId=Number(req.nextUrl.searchParams.get("eventId"))||undefined;return NextResponse.json(await listEventRegistrations(eventId));}catch(e){return apiError(e,'Etkinlik kayıtları alınamadı.');}}
export async function POST(req:NextRequest){const p=await portalSession(req);if(!p?.teamNum)return NextResponse.json({error:"Yetkisiz"},{status:401});try{const eventId=Number((await req.json()).eventId);if(!Number.isFinite(eventId)||eventId<=0)return NextResponse.json({error:'Geçersiz etkinlik.'},{status:400});const r=await registerEvent(p.teamNum,eventId);await audit(p.email,'register','event_registration',String(eventId),{team:p.teamNum});return NextResponse.json(r,{status:201});}catch(e:any){const message=String(e?.message||'');if(SAFE_ERRORS.includes(message))return NextResponse.json({error:message},{status:400});return apiError(e,'Etkinlik kaydı yapılamadı.');}}
export async function DELETE(req:NextRequest){try{const p=await portalSession(req);if(!p?.teamNum)return NextResponse.json({error:"Yetkisiz"},{status:401});const eventId=Number((await req.json()).eventId);if(!Number.isFinite(eventId)||eventId<=0)return NextResponse.json({error:'Geçersiz etkinlik.'},{status:400});await cancelEventRegistration(p.teamNum,eventId);await audit(p.email,'cancel','event_registration',String(eventId),{team:p.teamNum});return NextResponse.json({ok:true});}catch(e){return apiError(e,'Etkinlik kaydı iptal edilemedi.');}}
export async function PATCH(req:NextRequest){try{const s=await approvalsSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await req.json();const status=String(b.status||'').slice(0,30);if(status&&!['BEKLİYOR','ONAYLI','REDDEDİLDİ'].includes(status))return NextResponse.json({error:'Geçersiz kayıt durumu.'},{status:400});const r=await updateEventRegistration(Number(b.id),{...b,status});await audit(s.email,'update','event_registration',String(b.id),{status});return NextResponse.json(r);}catch(e){return apiError(e,'Etkinlik kaydı güncellenemedi.');}}
