"use client";
import {useEffect,useState} from "react";
import {uploadFile} from "@/lib/client-upload";
import {FigmaIcon} from "@/components/FigmaIcon";

const KEYS=['site_name','site_logo','site_mark','favicon_url','apple_touch_icon_url','og_image','hero_title','hero_description','hero_image','contact_team','contact_info','contact_phone','instagram','youtube','linkedin','maintenance','registration_fee_engage','registration_fee_achieve','registration_fee_inspire','registration_fee_adc','registration_fee_adc-pro','field_kit_fee','registration_discount'];
export default function Page(){
  const[s,setS]=useState<any>({ticker:[]}),[newTicker,setNewTicker]=useState(''),[msg,setMsg]=useState('');
  useEffect(()=>{fetch('/api/settings').then(r=>r.json()).then(x=>{let ticker=[];try{ticker=JSON.parse(x.ticker||'[]')}catch{}setS({...x,ticker})})},[]);
  const set=(k:string,v:any)=>setS((x:any)=>({...x,[k]:v}));
  async function upload(k:string,file?:File){if(!file)return;try{const u=await uploadFile('media',file);set(k,u.url);setMsg('Başarılı: Görsel yüklendi. Değişikliği kalıcı yapmak için Tüm Ayarları Kaydet butonuna basın.')}catch(e:any){setMsg('Hata: '+e.message)}}
  async function save(){try{const body:any={ticker:JSON.stringify(s.ticker||[])};for(const k of KEYS)body[k]=String(s[k]??'');const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const t=await r.text();let j:any={};try{j=t?JSON.parse(t):{}}catch{}if(!r.ok)throw new Error(j.error||t||`HTTP ${r.status}`);setMsg('Başarılı: Site ayarları kaydedildi.')}catch(e:any){setMsg('Hata: '+(e.message||'Kaydedilemedi.'))}}
  const i='mt-1 w-full rounded-md border-[1.5px] border-ink/20 bg-white px-3 py-2.5 text-[13px]';
  const asset=(k:string,label:string,help:string,previewClass='h-20 max-w-[260px] object-contain')=><label>{label}<input type="file" accept="image/*,.ico" className={i} onChange={e=>upload(k,e.target.files?.[0])}/><span className="mt-1 block text-[11px] leading-relaxed text-ink/45">{help}</span>{s[k]&&<img src={s[k]} alt={label} className={`mt-2 rounded border border-ink/10 bg-paper p-2 ${previewClass}`}/>}</label>;
  return <div className="max-w-5xl"><h1 className="flex items-center gap-2 font-display text-[25px] font-bold"><FigmaIcon name="ayarlar" className="h-7 w-7"/> SİTE AYARLARI</h1><p className="text-[13px] text-ink/55">Marka varlıkları, ana sayfa hero, iletişim, sosyal hesaplar, SEO görseli ve duyuru şeridi.</p>{msg&&<p className="mt-4 rounded-lg bg-cyan-deep/10 p-3 text-[13px] font-semibold text-cyan-deep">{msg}</p>}
  <section className="mt-5 rounded-xl border-2 border-ink bg-white p-5"><div className="mb-4"><p className="font-display text-[14px] font-bold">MARKA & WEB SİTESİ İKONLARI</p><p className="mt-1 text-[12px] text-ink/50">Header/footer logosu, marka işareti, tarayıcı ikonu ve paylaşım görselini buradan yönetin.</p></div><div className="grid gap-5 md:grid-cols-2"><label>Site adı<input className={i} value={s.site_name||''} onChange={e=>set('site_name',e.target.value)}/></label><div/>{asset('site_logo','Web sitesi ana logosu','Önerilen: 1000 × 280 px veya benzer yatay oran, şeffaf PNG / SVG yerine PNG-WebP. Header ve footer alanında kullanılır.')} {asset('site_mark','Kare marka işareti','Önerilen: 512 × 512 px (1:1), transparan PNG/WebP. Ana logo yüklenmemişse site adının yanında kullanılır.','h-24 w-24 object-contain')} {asset('favicon_url','Web sitesi ikonu / Favicon','Önerilen: 512 × 512 px (1:1), PNG veya ICO. Tarayıcı sekmesi ve küçük site ikonu için.','h-20 w-20 object-contain')} {asset('apple_touch_icon_url','Apple Touch Icon','Önerilen: 180 × 180 px (1:1), PNG. iPhone/iPad ana ekran ikonu için.','h-20 w-20 object-contain')} <div className="md:col-span-2">{asset('og_image','Sosyal paylaşım / Open Graph görseli','Önerilen: 1200 × 630 px. WhatsApp, LinkedIn ve sosyal ağlarda bağlantı paylaşım önizlemesi için.','h-40 w-full max-w-xl object-cover')}</div></div></section>
  <section className="mt-5 grid gap-4 rounded-xl border-2 border-ink bg-white p-5 md:grid-cols-2"><label>Hero başlık<input className={i} value={s.hero_title||''} onChange={e=>set('hero_title',e.target.value)}/></label><div/><label className="md:col-span-2">Hero açıklama<textarea rows={3} className={i} value={s.hero_description||''} onChange={e=>set('hero_description',e.target.value)}/></label><label className="md:col-span-2">Hero görseli<input type="file" accept="image/*" className={i} onChange={e=>upload('hero_image',e.target.files?.[0])}/><span className="mt-1 block text-[11px] leading-relaxed text-ink/45">Önerilen: <b>1600 × 1200 px</b> (4:3). JPG/WebP; ana sayfada 4:3 alanda gösterilir. Metinli görsel yerine temiz fotoğraf tercih edin.</span></label>{s.hero_image&&<img src={s.hero_image} alt="Hero" className="h-40 rounded-lg object-cover md:col-span-2"/>}</section>
  <section className="mt-5 rounded-xl border-2 border-ink bg-white p-5"><p className="flex items-center gap-2 font-display text-[13px] font-bold"><FigmaIcon name="anons" className="h-5 w-5"/> DUYURU ŞERİDİ</p><div className="mt-3 space-y-2">{(s.ticker||[]).map((t:string,idx:number)=><div key={idx} className="flex gap-2"><input className={i+' mt-0 flex-1'} value={t} onChange={e=>set('ticker',s.ticker.map((x:string,i:number)=>i===idx?e.target.value:x))}/><button onClick={()=>set('ticker',s.ticker.filter((_:string,i:number)=>i!==idx))} className="px-3 text-red-600">SİL</button></div>)}</div><div className="mt-3 flex gap-2"><input className={i+' mt-0 flex-1'} value={newTicker} onChange={e=>setNewTicker(e.target.value)} placeholder="Yeni duyuru"/><button onClick={()=>{if(newTicker.trim()){set('ticker',[...(s.ticker||[]),newTicker.trim()]);setNewTicker('')}}} className="rounded bg-cyan-brand px-4 font-bold">EKLE</button></div></section>
  <section className="mt-5 grid gap-4 rounded-xl border-2 border-ink bg-white p-5 md:grid-cols-2">{[['contact_team','Takım e-posta'],['contact_info','Genel e-posta'],['contact_phone','Telefon'],['instagram','Instagram'],['youtube','YouTube'],['linkedin','LinkedIn']].map(([k,l])=><label key={k}>{l}<input className={i} value={s[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}</section>
  <section className="mt-5 grid gap-4 rounded-xl border-2 border-ink bg-white p-5 md:grid-cols-4"><p className="md:col-span-4 font-display text-[13px] font-bold">KAYIT ÜCRETLERİ (TL)</p>{[['registration_fee_engage','ENG'],['registration_fee_achieve','ACH'],['registration_fee_inspire','INS'],['registration_fee_adc','ADC'],['registration_fee_adc-pro','PRO'],['field_kit_fee','Saha Kiti'],['registration_discount','İndirim']].map(([k,l])=><label key={k}>{l}<input type="number" className={i} value={s[k]||'0'} onChange={e=>set(k,e.target.value)}/></label>)}</section>
  <button onClick={save} className="mt-5 rounded-md bg-ink px-6 py-3 font-display text-[13px] font-bold text-white">TÜM AYARLARI KAYDET</button></div>
}
