"use client";
import {useEffect,useState} from "react";
export default function Page(){
  const [d,setD]=useState<any>(null),[err,setErr]=useState("");
  const load=async()=>{setErr("");try{const r=await fetch("/api/system/diagnostics",{cache:"no-store"});const t=await r.text();const j=t?JSON.parse(t):{};if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);setD(j)}catch(e:any){setErr(e.message)}};
  useEffect(()=>{load()},[]);
  const Badge=({ok}:{ok:boolean})=><span className={`rounded px-2 py-1 text-[11px] font-bold ${ok?"bg-green-100 text-green-700":"bg-red-100 text-red-700"}`}>{ok?"OK":"HATA"}</span>;
  return <div className="max-w-5xl"><div className="flex items-center justify-between"><div><h1 className="font-display text-[25px] font-bold">SİSTEM TANILAMA</h1><p className="text-[13px] text-ink/55">Vercel environment, Supabase PostgreSQL ve Storage durumunu doğrular.</p></div><button onClick={load} className="rounded bg-ink px-4 py-2 text-xs font-bold text-white">YENİDEN TEST ET</button></div>{err&&<p className="mt-4 rounded bg-red-50 p-3 text-sm font-semibold text-red-700">⚠ {err}</p>}{d&&<div className="mt-5 grid gap-4 md:grid-cols-2"><section className="rounded-xl border-2 border-ink bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-display font-bold">VERİTABANI</h2><Badge ok={!!d.db?.ok}/></div><p className="mt-3 text-sm">DATABASE_URL: <b>{d.db?.env?.databaseUrl?"var":"yok"}</b></p><p className="mt-1 text-sm">Database: <b>{d.db?.database?.database||"—"}</b></p><p className="mt-1 text-sm">User: <b>{d.db?.database?.db_user||"—"}</b></p>{d.db?.missingTables?.length>0&&<p className="mt-3 rounded bg-red-50 p-2 text-xs text-red-700">Eksik tablo: {d.db.missingTables.join(", ")}</p>}{d.db?.error&&<p className="mt-3 text-xs text-red-700">{d.db.error}</p>}</section><section className="rounded-xl border-2 border-ink bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-display font-bold">SUPABASE STORAGE</h2><Badge ok={!!d.storage?.ok}/></div><p className="mt-3 text-sm">SUPABASE_URL: <b>{d.storage?.env?.supabaseUrl?"var":"yok"}</b></p><p className="mt-1 text-sm">Secret key: <b>{d.storage?.env?.secretKey?"var":"yok"}</b></p><p className="mt-3 text-xs text-ink/60">Bucketlar: {(d.storage?.buckets||[]).map((b:any)=>`${b.id} (${b.public?"public":"private"})`).join(", ")||"—"}</p>{d.storage?.error&&<p className="mt-3 text-xs text-red-700">{d.storage.error}</p>}</section><section className="rounded-xl border-2 border-ink bg-white p-5 md:col-span-2"><h2 className="font-display font-bold">OTURUM / VERCEL ENV</h2><div className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><p>SESSION_SECRET: <b>{d.env?.sessionSecret?"var":"yok"}</b></p><p>ADMIN_EMAIL: <b>{d.env?.adminEmail?"var":"yok"}</b></p><p>ADMIN_PASSWORD: <b>{d.env?.adminPassword?"var":"yok"}</b></p></div><p className="mt-3 text-xs text-ink/45">Sürüm: {d.version}</p></section></div>}</div>
}
