import {NextRequest,NextResponse} from "next/server";
import {contentSession} from "@/lib/auth";
import {audit,deleteNews,getNews,listNews,slugify,upsertNews} from "@/lib/db";
import {pathFromPublicUrl,PUBLIC_BUCKET,removeObject} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
import {cleanText,validHttpUrl} from "@/lib/security";
export const dynamic="force-dynamic";
async function cleanup(url?:string){const p=pathFromPublicUrl(url);if(p)await removeObject(PUBLIC_BUCKET,p).catch(()=>{});}
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await contentSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listNews(all));}catch(e){return apiError(e,'Haberler alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'CMS içerik düzenleme yetkisi gerekli.'},{status:401});const raw=await req.json();const title=cleanText(raw.title,220),slug=slugify(cleanText(raw.slug||title,120));if(!slug||!title)return NextResponse.json({error:'Başlık ve slug zorunlu'},{status:400});const cover=cleanText(raw.cover_url,1000);if(cover&&!validHttpUrl(cover))return NextResponse.json({error:'Kapak görseli URL’si geçersiz.'},{status:400});const b={...raw,slug,title,tag:cleanText(raw.tag||'DUYURU',40),excerpt:cleanText(raw.excerpt,1200),body:cleanText(raw.body,100000),cover_url:cover,author:cleanText(raw.author||'RECF Türkiye',120),date:cleanText(raw.date,64)||new Date().toISOString(),published:!!raw.published,featured:!!raw.featured};const old:any=await getNews(slug,true);const r=await upsertNews(b);if(old?.cover_url&&old.cover_url!==r.cover_url)await cleanup(old.cover_url);await audit(s.email,'save','news',slug,{title});return NextResponse.json(r,{status:201});}catch(e){return apiError(e,'Haber/duyuru kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const slug=slugify(cleanText((await req.json()).slug,120));if(!slug)return NextResponse.json({error:'Geçersiz içerik.'},{status:400});const old:any=await getNews(slug,true);await deleteNews(slug);if(old?.cover_url)await cleanup(old.cover_url);await audit(s.email,'delete','news',slug);return NextResponse.json({ok:true});}catch(e){return apiError(e,'İçerik silinemedi.');}}
