import {NextRequest,NextResponse} from "next/server";
import {contentSession} from "@/lib/auth";
import {audit,deleteProgram,getProgram,listPrograms,saveProgram,slugify} from "@/lib/db";
import {pathFromPublicUrl,PUBLIC_BUCKET,removeObject} from "@/lib/storage";
import {apiError} from "@/lib/api-server";
import {cleanText,validHttpUrl} from "@/lib/security";
export const dynamic="force-dynamic";
async function cleanup(url?:string){const p=pathFromPublicUrl(url);if(p)await removeObject(PUBLIC_BUCKET,p).catch(()=>{});}
const arr=(v:any,max=20)=>Array.isArray(v)?v.slice(0,max):[];
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get('all')==='1';if(all&&!(await contentSession(req)))return NextResponse.json({error:'Yetkisiz'},{status:401});return NextResponse.json(await listPrograms(all));}catch(e){return apiError(e,'Programlar alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'CMS içerik düzenleme yetkisi gerekli.'},{status:401});const raw=await req.json();const slug=slugify(cleanText(raw.slug||raw.name,100)),code=cleanText(raw.code,30),name=cleanText(raw.name,140);if(!slug||!code||!name)return NextResponse.json({error:'Slug, kod ve ad zorunlu'},{status:400});const cover=cleanText(raw.cover_url,1000);if(cover&&!validHttpUrl(cover))return NextResponse.json({error:'Kapak görseli URL’si geçersiz.'},{status:400});let source=cleanText(raw.source,1000);if(source&&!/^https?:\/\//i.test(source))source=`https://${source}`;if(source&&!validHttpUrl(source))return NextResponse.json({error:'Kaynak URL geçersiz.'},{status:400});const chips=arr(raw.chips).map(x=>cleanText(x,80)).filter(Boolean);const match_types=arr(raw.match_types,12).map((x:any)=>({title:cleanText(x?.title,120),desc:cleanText(x?.desc,500),icon:cleanText(x?.icon,30)}));const facts=arr(raw.facts,20).map((x:any)=>({label:cleanText(x?.label,100),value:cleanText(x?.value,200)}));const b={...raw,slug,code,name,game:cleanText(raw.game,160),age:cleanText(raw.age,80),age_detail:cleanText(raw.age_detail,180),color_hex:/^#[0-9A-F]{6}$/i.test(String(raw.color_hex||''))?String(raw.color_hex):'#29B9E5',short:cleanText(raw.short,1000),long:cleanText(raw.long,50000),chips,match_types,facts,source,cover_url:cover,active:raw.active!==false,sort_order:Math.max(0,Math.min(9999,Number(raw.sort_order)||0))};const old:any=await getProgram(slug,true);const r=await saveProgram(b);if(old?.cover_url&&old.cover_url!==r.cover_url)await cleanup(old.cover_url);await audit(s.email,'save','program',r.slug,{name:r.name});return NextResponse.json(r,{status:201});}catch(e){return apiError(e,'Program kaydedilemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:'Yetkisiz'},{status:401});const slug=slugify(cleanText((await req.json()).slug,100));if(!slug)return NextResponse.json({error:'Geçersiz program.'},{status:400});const old:any=await getProgram(slug,true);await deleteProgram(slug);if(old?.cover_url)await cleanup(old.cover_url);await audit(s.email,'disable','program',slug);return NextResponse.json({ok:true});}catch(e){return apiError(e,'Program pasife alınamadı.');}}
