import { NextRequest, NextResponse } from "next/server";
import { contentSession } from "@/lib/auth";
import { addMedia, audit, deleteMedia, listMedia, updateMedia } from "@/lib/db";
import { PUBLIC_BUCKET, PUBLIC_MIME, publicUrlMatchesPath, removeObject, safeStoragePath, verifyStoredObject } from "@/lib/storage";
import {apiError} from "@/lib/api-server";
import {cleanText} from "@/lib/security";
export const dynamic="force-dynamic";
export async function GET(req:NextRequest){try{const all=req.nextUrl.searchParams.get("all")==="1";if(all&&!(await contentSession(req)))return NextResponse.json({error:"Yetkisiz"},{status:403});return NextResponse.json(await listMedia(all));}catch(e){return apiError(e,'Medya listesi alınamadı.');}}
export async function POST(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:"CMS içerik düzenleme yetkisi gerekli."},{status:403});const b=await req.json();const title=cleanText(b.title,160),path=cleanText(b.path,500),url=cleanText(b.url,1200);if(!title||!path||!url||!safeStoragePath(path,'media')||!publicUrlMatchesPath(url,path))return NextResponse.json({error:"Başlık veya yüklenen medya yolu geçersiz"},{status:400});const verified=await verifyStoredObject(PUBLIC_BUCKET,path,PUBLIC_MIME,25*1024*1024);if(!verified.ok)return NextResponse.json({error:verified.error},{status:400});const r=await addMedia({...b,title,path,url,mime_type:verified.mime,size_bytes:verified.size,alt_text:cleanText(b.alt_text,250),caption:cleanText(b.caption,1000),event_slug:cleanText(b.event_slug,80),type:cleanText(b.type,20)});await audit(s.email,"create","media",String(r.id),{title});return NextResponse.json(r,{status:201});}catch(e){return apiError(e,'Medya kaydedilemedi.');}}
export async function PUT(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const b=await req.json();const r=await updateMedia(Number(b.id),{...b,title:cleanText(b.title,160),event_slug:cleanText(b.event_slug,80),alt_text:cleanText(b.alt_text,250),caption:cleanText(b.caption,1000),type:cleanText(b.type,20)});await audit(s.email,'update','media',String(b.id),{title:r?.title});return NextResponse.json(r);}catch(e){return apiError(e,'Medya güncellenemedi.');}}
export async function DELETE(req:NextRequest){try{const s=await contentSession(req);if(!s)return NextResponse.json({error:"Yetkisiz"},{status:403});const {id}=await req.json();const r=await deleteMedia(Number(id));if(r?.path&&safeStoragePath(String(r.path),'media'))await removeObject(PUBLIC_BUCKET,r.path).catch(()=>{});await audit(s.email,"delete","media",String(id));return NextResponse.json({ok:true});}catch(e){return apiError(e,'Medya silinemedi.');}}
