import type {Metadata} from "next";
import Link from "next/link";
import {pageMeta} from "@/lib/seo";
import {COMMITTEE_AREAS} from "@/lib/planning-committee";
import {PUBLIC_CONTACT} from "@/lib/public-contact";
import {provinces} from "@/lib/locations";
import {FigmaIcon} from "@/components/FigmaIcon";
import PlanningCommitteeForm from "@/components/public/PlanningCommitteeForm";
export const metadata:Metadata=pageMeta({title:"Planlama Komitesi ve Gönüllü Başvurusu",description:"RECF Türkiye Planlama Komitesi: etkinlik hazırlığı, eğitim, iletişim ve gönüllü koordinasyonuna katkı sun. Yetişkin gönüllüler için başvuru formu.",path:"/planlama-komitesi"});
const process=[{title:"BAŞVURUNU PAYLAŞ",text:"Katkı alanlarını, deneyimini ve uygunluğunu formda anlat."},{title:"EKİBİMİZ İNCELER",text:"İhtiyaçlar ve çalışma alanları doğrultusunda başvurun değerlendirilir."},{title:"BİRLİKTE NETLEŞTİRELİM",text:"Uygun başvurularda görev, zaman ve çalışma biçimi görüşmede birlikte belirlenir."}];
export default function PlanningCommitteePage(){
  return <div className="pb-20">
    <section className="field-grid relative overflow-hidden border-b-2 border-ink">
      <div className="safe-x mx-auto grid max-w-7xl gap-8 py-12 lg:grid-cols-[1.3fr_.7fr] lg:px-10 lg:py-20">
        <div><p className="inline-flex items-center gap-2 rounded bg-ink px-3 py-2 font-display text-xs font-bold tracking-[1.5px] text-cyan-brand"><FigmaIcon name="ittifak" className="h-5 w-5"/> PLANLAMA KOMİTESİ</p><h1 className="mt-5 font-display text-[clamp(2.5rem,8vw,4.75rem)] font-bold leading-[.98]">SAHAYI BİRLİKTE<br/><span className="text-cyan-deep">HAZIRLAYALIM.</span></h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-ink/65">Bir etkinliğin gücü, hazırlığı birlikte yapan ekibinden gelir. RECF Türkiye Planlama Komitesi; etkinlik, eğitim ve topluluk süreçlerine deneyimini ve zamanını paylaşarak katkı sunmak isteyen yetişkin gönüllüleri bir araya getirir.</p><a href="#basvuru" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-md border-2 border-ink bg-ink px-5 py-3 font-display text-sm font-bold text-white shadow-plateSm shadow-cyan-brand">GÖNÜLLÜ OL →</a></div>
        <div className="self-end rounded-xl border-2 border-ink bg-white p-6 shadow-plate shadow-cyan-brand/40"><p className="font-display text-xs font-bold tracking-[2px] text-cyan-deep">AYNI HEDEF. FARKLI UZMANLIKLAR.</p><div className="mt-5 space-y-4">{["Etkinlik hazırlığı ve koordinasyon","Takım ve mentör ihtiyaçları","Topluluk, okul ve paydaş iletişimi"].map((text,index)=><p key={text} className="flex items-center gap-3 border-b border-ink/10 pb-4 font-display text-sm font-semibold last:border-0 last:pb-0"><span className="text-2xl font-bold text-cyan-deep">0{index+1}</span>{text}</p>)}</div></div>
      </div>
    </section>
    <div className="safe-x mx-auto max-w-7xl lg:px-10">
      <section className="grid gap-6 py-12 lg:grid-cols-[1fr_1.5fr]"><div><p className="font-display text-xs font-bold tracking-[2px] text-cyan-deep">KOMİTE NE YAPAR?</p><h2 className="mt-3 font-display text-3xl font-bold leading-tight">HAZIRLIKTA DÜZEN.<br/>SAHADA GÜÇLÜ BİR EKİP.</h2></div><div className="space-y-4 text-[15px] leading-relaxed text-ink/65"><p>Komite; fikirleri uygulanabilir hazırlık adımlarına dönüştürmeye, ihtiyaçları önceden belirlemeye ve ekipler arasındaki iletişimi düzenlemeye katkı sunar. Yerel ihtiyaçlar, gönüllülerin deneyimi ve etkinlik hazırlıkları birlikte değerlendirilir.</p><p>Gönüllü katkı alanın ve ayırabileceğin zaman, görev paylaşımının temelidir. Çalışma takvimi, toplantılar ve etkinlik günü görevleri başvuru değerlendirmesi sonrasında ayrıca paylaşılır.</p></div></section>
      <section className="border-t border-ink/15 py-12"><p className="font-display text-xs font-bold tracking-[2px] text-cyan-deep">KATKI ALANLARI</p><h2 className="mt-3 font-display text-3xl font-bold">DENEYİMİNLE BİR ALANA GÜÇ KAT.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{COMMITTEE_AREAS.map((area,index)=><article key={area.id} className="rounded-lg border-2 border-ink bg-white p-5"><p className="font-display text-sm font-bold text-cyan-deep">0{index+1}</p><h3 className="mt-3 font-display text-lg font-bold">{area.label}</h3><p className="mt-2 text-sm leading-relaxed text-ink/60">{area.description}</p></article>)}</div></section>
      <section className="grid gap-6 border-t border-ink/15 py-12 lg:grid-cols-2"><div className="rounded-xl bg-ink p-6 text-white sm:p-8"><p className="font-display text-xs font-bold tracking-[2px] text-cyan-brand">KİMLER BAŞVURABİLİR?</p><h2 className="mt-3 font-display text-2xl font-bold">KATKI SUNMAK İSTEYEN YETİŞKİN GÖNÜLLÜLER.</h2><p className="mt-4 text-sm leading-relaxed text-white/70">Mentörler, eğitimciler, teknik uzmanlar, iletişim ve organizasyon deneyimi olan yetişkinler; bir kuruma bağlı olarak veya bağımsız biçimde başvurabilir. Katkı alanını ve uygunluğunu açıkça paylaşman yeterli.</p><p className="mt-3 text-sm leading-relaxed text-white/70">Gönüllü başvurusu görev ataması veya komite üyeliği garantisi değildir. İhtiyaçlar ve karşılıklı uygunluk görüşmede netleştirilir.</p></div><div className="space-y-5">{process.map((step,index)=><div key={step.title} className="flex gap-4 rounded-lg border border-ink/20 bg-white p-5"><span className="font-display text-2xl font-bold text-cyan-deep">{index+1}</span><div><h3 className="font-display text-sm font-bold">{step.title}</h3><p className="mt-1 text-sm leading-relaxed text-ink/60">{step.text}</p></div></div>)}</div></section>
      <section id="basvuru" className="scroll-mt-28 grid gap-7 border-t-2 border-ink pt-12 lg:grid-cols-[1.6fr_.8fr]"><PlanningCommitteeForm provinces={provinces()}/><aside className="self-start rounded-xl border-2 border-ink bg-white p-6 lg:sticky lg:top-28"><p className="font-display text-xs font-bold tracking-[2px] text-cyan-deep">BAŞVURU ÖNCESİ</p><h2 className="mt-3 font-display text-2xl font-bold">NEREDEN BAŞLAYABİLİRİM?</h2><p className="mt-4 text-sm leading-relaxed text-ink/60">Sana uygun bir ile üç katkı alanı seç. Deneyimini kısa ve somut örneklerle anlat; ne zaman katkı sunabileceğini belirt.</p><p className="mt-3 text-sm leading-relaxed text-ink/60">Başvurun kaydedildiğinde e-posta ile alındı bilgilendirmesi gönderilir. Ekibimiz değerlendirme ve sonraki adımlar için seninle iletişime geçer.</p><a href={`mailto:${PUBLIC_CONTACT.events}`} className="mt-5 block break-all font-semibold text-cyan-deep underline">{PUBLIC_CONTACT.events}</a><Link href="/hakkimizda" className="mt-5 inline-block font-display text-xs font-bold">RECF TÜRKİYE’Yİ TANI →</Link></aside></section>
    </div>
  </div>;
}
